
USE [master];
GO


GO

USE nwind;
GO

set statistics io, time on

-- Compare execution time and distinct counts
ALTER DATABASE Nwind SET COMPATIBILITY_LEVEL = 130;

SELECT COUNT(DISTINCT Orderid)
FROM [Order Details]
OPTION (USE HINT('DISALLOW_BATCH_MODE'), RECOMPILE); -- Isolating out BMOR

ALTER DATABASE Nwind SET COMPATIBILITY_LEVEL = 160;
GO
SELECT APPROX_COUNT_DISTINCT( Orderid)
FROM [Order Details]
OPTION (USE HINT('DISALLOW_BATCH_MODE'), RECOMPILE); -- Isolating out BMOR


 ALTER DATABASE Nwind SET COMPATIBILITY_LEVEL = 130;

SELECT COUNT(DISTINCT country)
FROM customers
OPTION (USE HINT('DISALLOW_BATCH_MODE'), RECOMPILE); -- Isolating out BMOR

ALTER DATABASE Nwind SET COMPATIBILITY_LEVEL = 160;
GO
SELECT APPROX_COUNT_DISTINCT( country)
FROM customers
OPTION (USE HINT('DISALLOW_BATCH_MODE'), RECOMPILE); 